# models.py
from django.db import models

class Worker(models.Model):
    id = models.CharField(primary_key=True, max_length=100)
    name = models.CharField(max_length=100)
    birth_date = models.DateField(null=True, blank=True)
    location_lat = models.FloatField()
    location_lng = models.FloatField()
    preferred_tags = models.JSONField()
    experience_level = models.CharField(max_length=20)
    skills = models.JSONField()
    profile_photo = models.URLField()
    cv_url = models.URLField(null=True, blank=True)
    availability = models.BooleanField(default=True)
    profile_score = models.IntegerField(default=0)
    swipe_stats = models.JSONField(default=dict)
    created_at = models.DateTimeField(auto_now_add=True)

class Job(models.Model):
    id = models.CharField(primary_key=True, max_length=100)
    business_id = models.CharField(max_length=100)
    title = models.CharField(max_length=255)
    description = models.TextField()
    tags = models.JSONField()
    experience_required = models.CharField(max_length=20)
    skills_needed = models.JSONField()
    location_lat = models.FloatField()
    location_lng = models.FloatField()
    salary_min = models.FloatField()
    salary_max = models.FloatField()
    is_active = models.BooleanField(default=True)
    applicants = models.JSONField(default=list)
    matches = models.JSONField(default=list)
    rejected = models.JSONField(default=dict)
    created_at = models.DateTimeField(auto_now_add=True)