# Generated by Django 5.1.6 on 2025-04-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_product_createdtime_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.JSONField()),
                ('experience_required', models.CharField(max_length=20)),
                ('skills_needed', models.JSONField()),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('salary_min', models.FloatField()),
                ('salary_max', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('applicants', models.JSONField(default=list)),
                ('matches', models.JSONField(default=list)),
                ('rejected', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('preferred_tags', models.JSONField()),
                ('experience_level', models.CharField(max_length=20)),
                ('skills', models.JSONField()),
                ('profile_photo', models.URLField()),
                ('cv_url', models.URLField(blank=True, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('profile_score', models.IntegerField(default=0)),
                ('swipe_stats', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
